linter:
  rules:
    - prefer_single_quotes
    - always_specify_types
    - avoid_print
    - unnecessary_new
    - prefer_const_constructors
    - prefer_final_fields
    - type_annotate_public_apis
    - public_member_api_docs
    - lines_longer_than_80_chars
    - avoid_annotating_with_dynamic
    - prefer_is_empty
    - unnecessary_this
    - prefer_typing_uninitialized_variables
    - use_key_in_widget_constructors