version: '3.8'

services:
  shortener:
    build: .
    container_name: url-shortener
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - shortener-network
    env_file:
      - src/.env

  postgres:
    image: postgres:14
    container_name: url-shortener-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shortener-network

  redis:
    image: redis:alpine
    container_name: url-shortener-redis
    networks:
      - shortener-network

volumes:
  postgres-data:

networks:
  shortener-network:
    driver: bridge
