"""add click_count

Revision ID: 10fcacf444f5
Revises: 7fb14d84937a
Create Date: 2025-06-17 18:48:24.486887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10fcacf444f5'
down_revision: Union[str, None] = '7fb14d84937a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortenedurl', sa.Column('click_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortenedurl', 'click_count')
    # ### end Alembic commands ###
