"""add max_clicks to shortened_url

Revision ID: 310fb07545fb
Revises: 10fcacf444f5
Create Date: 2025-06-18 12:31:10.485901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '310fb07545fb'
down_revision: Union[str, None] = '10fcacf444f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortenedurl', sa.Column('max_clicks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortenedurl', 'max_clicks')
    # ### end Alembic commands ###
