"""Add custom_domain to shortenedurl

Revision ID: 48e88904ee6f
Revises: b47b34e94f97
Create Date: 2025-06-14 11:04:50.882132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48e88904ee6f'
down_revision: Union[str, None] = 'b47b34e94f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortenedurl', sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('shortenedurl', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_shortenedurl_custom_domain'), 'shortenedurl', ['custom_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortenedurl_custom_domain'), table_name='shortenedurl')
    op.alter_column('shortenedurl', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('shortenedurl', 'custom_domain')
    # ### end Alembic commands ###
