"""support duration in mins, hours, days, months, years

Revision ID: 7fb14d84937a
Revises: 48e88904ee6f
Create Date: 2025-06-16 11:12:31.283808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fb14d84937a'
down_revision: Union[str, None] = '48e88904ee6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shortenedurl_short_url', table_name='shortenedurl')
    op.create_index(op.f('ix_shortenedurl_short_url'), 'shortenedurl', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortenedurl_short_url'), table_name='shortenedurl')
    op.create_index('ix_shortenedurl_short_url', 'shortenedurl', ['short_url'], unique=False)
    # ### end Alembic commands ###
